workflows:
  react-native-android:
    name: React Native Android Dry Run
    max_build_duration: 60
    environment:
      node: 18.16.0
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Clean and build unsigned APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
